name: Deploy Web

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar tests
        run: npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Subir artefacto para GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: .

      - name: Desplegar en GitHub Pages
        uses: actions/deploy-pages@v2